ARG DEBIAN_VERSION=trixie
FROM docker.io/arm32v7/debian:$DEBIAN_VERSION-slim

ARG KERNEL_VERSION=6.1.115
ARG DEBIAN_VERSION=trixie

COPY ./kernel-$KERNEL_VERSION/ /boot/
RUN mkdir -p /lib/modules && mv /boot/$KERNEL_VERSION-steam /lib/modules/$KERNEL_VERSION-steam

COPY ./rootfs/boot/* /boot/
COPY ./rootfs/usr/bin/* /usr/bin/
COPY ./rootfs/steamlink/ /steamlink/

# Add repositories (trixie uses non-free-firmware)
RUN rm -rf /etc/apt/sources.list.d/* || true
RUN echo "deb http://deb.debian.org/debian $DEBIAN_VERSION main contrib non-free non-free-firmware" > /etc/apt/sources.list
RUN echo "deb http://security.debian.org/debian-security $DEBIAN_VERSION-security main contrib non-free non-free-firmware" >> /etc/apt/sources.list
RUN echo "deb http://deb.debian.org/debian $DEBIAN_VERSION-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list

# Install basic system components
RUN apt-get update && apt-get install -y --no-install-recommends \
    systemd systemd-sysv systemd-timesyncd dbus ca-certificates dhcpcd5 nano vim \
    openssh-server sudo ifupdown net-tools udev iputils-ping wget \
    dosfstools unzip binutils libatomic1 initramfs-tools e2fsprogs \
    parted firmware-libertas wireless-regdb wpasupplicant iw \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# Create initramfs
RUN mkinitramfs -o /boot/initramfs-linux-steam.img $KERNEL_VERSION-steam

RUN useradd -s /bin/bash -m debian
RUN echo "debian:steamlink" | chpasswd
RUN usermod -a -G sudo debian

# Enable basic services
RUN systemctl enable ssh dbus networking systemd-timesyncd

# /etc/network/interfaces setup
RUN echo "allow-hotplug eth0" > /etc/network/interfaces
RUN echo "auto eth0" >> /etc/network/interfaces
RUN echo "iface eth0 inet dhcp" >> /etc/network/interfaces
